### GET request to example server
POST localhost:14399/api/v1/vehicle/addVehicle
Content-Type: application/json

{
  "vehicle": {
    "vehicleNumber": "ABC-12348",
    "passengerCount": 5,
    "vehicleType": "Seda",
    "pricePerKm": 15.50,
    "basePrice": 100.00,
    "availabilityFrom": "2025-04-30",
    "availabilityTo": "2025-05-30",
    "description": "Well-maintained Toyota Corollaaa"
  },
  "availability": {
    "availabilityFrom": "2025-04-30",
    "availabilityTo": "2025-05-30"
  },
  "owner": {
    "name": "John Doe",
    "contactNumber": "+94771234567",
    "nic": "941234567V"
  },
  "images": [
    {
      "imageUrl": "https://example.com/images/abc1234_1.jpg ",
      "uploadedAt": "2025-03-31T10:00:00"
    },
    {
      "imageUrl": "https://example.com/images/abc1234_2.jpg ",
      "uploadedAt": "2025-04-30T10:05:00"
    }
  ]
}

###